### ISSUE TITLE
Can I use this software on plants?

### ISSUE THREAD

**Issue by hanshanmengqi** [WangJiuming/YOLOOP#1]
Hi,

Thank you for your interesting software.

I work with plants, and I’m wondering if I can use your software for plant-related data without the need for re-training.

Best,
Han

**Comment by WangJiuming** [comment]
Hi Han,

Thanks for your interest in our work!

Based on our experience, our pre-trained model would have a better chance to work well if the target contact matrix is obtained with the same experiment protocol (e.g., Hi-C, Micro-C, etc.). It's also possible to fine-tune our pre-trained model on your plant data, which would probably be easier and more effective than re-training from scratch.

Feel free to let us know if you need any further help.

**Comment by WangJiuming** [comment]
Closing this for now. Feel free to re-open if there's any further question :)
