### ISSUE TITLE
Request for Supplementary Information

### ISSUE THREAD

**Issue by YusenHou519** [WangJiuming/YOLOOP#2]
Dear Siyuan and Jiuming,

I hope this message finds you well.

My name is Yusen, and I am currently pursuing my Master's degree, focusing on 3D genome research. I came across your fascinating work in this area and found it extremely impressive. I am eager to learn more about your research.

If possible, could you kindly share the supplementary information with me? You can send it to my email: houys01@outlook.com.

Thank you very much for your time and consideration. I look forward to your response.

Best regards,
Yusen

**Comment by WangJiuming** [comment]
Hi Yusen,

Thanks for your interest in our work! 

However, the manuscript is still with the editor. We expect the full version, including supplementary information, to be published shortly in the coming weeks. In the meanwhile, feel free to let us know if there's any specific information you need.
