### ISSUE TITLE
The questions about the visualization of detect results

### ISSUE THREAD

**Issue by qqyanyang** [WangJiuming/YOLOOP#5]
Hello, I have recently started to study bioinformatics and I would like to ask you some questions. After using  detcet.py  to achieve reproduction and generating the bedpe format file, how should I visualize it? Thanks a lot！

**Comment by WangJiuming** [comment]
Hi, thanks for your interest in our work!

To visualize the results predicted by YOLOOP, generally you can follow the steps below:
1. first select a region of interest (e.g., `chr14:33,000,000:36,000,000`);
2. read the `bedpe` file and filter the predicted loops within this region;
3. plot the contact map of this region (e.g., as a heatmap) together with the filtered loops (e.g., as dots)

Feel free to let us know if you have any follow-up questions.

Best,
Jiuming

**Comment by qqyanyang** [comment]
Thanks for your patience，and I'll give it a try. Thanks a lot!

**Comment by WangJiuming** [comment]
No problem. Closing this for now. Feel free to re-open if there's any further question :)
